"""Compact argument contracts shared with the model and tool catalog."""
ARGUMENTS = {
    "projects.list": {"pending": "boolean, default true. List open projects; false includes completed projects. No project ID required."},
    "daily.summary": {},
    "schedules.list": {},
    "schedules.update": {"id": "existing ID or exact title", "title": "exact existing title", "changes": "object: enabled boolean, title, goal, mode CHAT|ASK|PLAN|DO|RESEARCH, run_at future ISO8601 with timezone, interval_minutes 0 or 5..10080"},
    "schedules.delete": {"id": "existing ID or exact title", "title": "exact existing title"},
    "items.list": {"kind": "tasks|projects", "query": "optional title search"},
    "items.create": {"kind": "tasks|projects", "values": "object: title, description, project_id, priority LOW|MEDIUM|HIGH, due YYYY-MM-DD"},
    "items.update": {"kind": "tasks|projects", "id": "existing ID or omit with full title", "title": "full existing title", "changes": "object of fields to change: title,description,status,priority,due,project_id"},
    "items.delete": {"kind": "tasks|projects", "id": "existing ID or omit with full title", "title": "full existing title"},
    "tasks.list": {"due": "optional YYYY-MM-DD; only tasks due that day", "query": "optional title search"}, "projects.summary": {"project_id": "required existing project ID when no project selected"},
    "projects.create": {"title": "required text", "description": "optional text", "due": "optional YYYY-MM-DD deadline"},
    "tasks.create": {"title": "required text", "description": "optional text", "priority": "LOW|MEDIUM|HIGH", "due": "optional YYYY-MM-DD deadline", "project_id": "optional existing project ID"},
    "memory.search": {"query": "text"}, "documents.search": {"query": "text"},
    "decisions.create": {"title": "required text", "content": "required decision and rationale"},
    "report.create": {"title": "required text", "content": "required Markdown"},
    "workspace.list": {"path": "relative folder, default .", "limit": "1..500"},
    "workspace.read": {"path": "required relative UTF-8 file"},
    "workspace.write": {"path": "required relative file", "content": "required text", "overwrite": "boolean, false by default"},
    "code.scaffold": {"name": "required new folder, must not exist", "kind": "web|app|game; app and game are fixed starter templates", "description": "optional text", "html": "required for web: complete custom HTML matching the request", "css": "optional stylesheet", "javascript": "optional browser JavaScript"},
    "game.scaffold": {"name": "required new folder", "description": "optional text"},
    "code.run": {"path": "required file or tests folder", "runner": "python|node|unittest|pytest", "timeout_seconds": "1..60"},
    "git.status": {"path": "relative repository folder"}, "git.diff": {"path": "relative repository folder", "staged": "boolean"},
    "git.branch": {"path": "relative repository folder", "name": "required new branch name"},
    "security.audit": {"path": "relative folder"}, "devops.diagnose": {"path": "relative folder"},
    "study.create": {"title": "required text", "content": "required study notes", "days": "1..90"},
    "files.create": {"title": "required text", "content": "required text", "format": "md|txt|html|csv", "path": "optional relative file"},
    "calendar.list": {"from": "optional ISO8601 with timezone", "to": "optional ISO8601 with timezone"},
    "calendar.create": {"title": "required text", "start": "required ISO8601 with timezone", "end": "optional ISO8601 with timezone", "description": "optional text"},
    "email.draft": {"to": "required email", "subject": "required text", "body": "required text"},
    "automation.create": {"title": "required text", "goal": "required text", "run_at": "required future ISO8601 with timezone", "interval_minutes": "0 once or 5..10080", "mode": "CHAT by default; legacy ASK|PLAN|DO|RESEARCH"},
    "google_calendar.list": {"start": "optional ISO8601 with timezone, beginning of requested interval", "end": "optional ISO8601 with timezone, exclusive end", "query": "optional text", "limit": "1..100", "page_token": "optional token from previous result", "calendar_id": "optional, default primary"},
    "google_calendar.create": {"title": "required text", "start": "required ISO8601 with timezone", "end": "required ISO8601 with timezone", "description": "optional text", "location": "optional text"},
    "email.list": {"query": "Gmail search; in:inbox for received mail, newer_than:7d for last 7 days", "limit": "1..20, use requested message count; default 10", "page_token": "optional token from previous result"}, "email.read": {"id": "required message ID"},
    "email.send": {"to": "required email", "subject": "required text", "body": "required plain text"},
    "github.inspect": {"repository": "required owner/repo"},
    "github.tree": {"repository": "required owner/repo", "ref": "optional branch/ref"},
    "github.read": {"repository": "required owner/repo", "path": "required repository file", "ref": "optional branch/ref"},
    "github.diff": {"repository": "required owner/repo", "base": "required ref", "head": "required ref"},
    "github.branch": {"repository": "required owner/repo", "branch": "required new branch", "from_ref": "optional ref"},
    "github.write": {"repository": "required owner/repo", "path": "required file", "branch": "required branch", "message": "required commit message", "content": "required text", "sha": "reviewed SHA required when replacing existing file"},
    "web.search": {"query": "required text, max 500 chars", "limit": "1..20"},
    "n8n.trigger": {"payload": "JSON object"}, "drive.list": {"query": "optional text"},
    "drive.read": {"id": "required file ID"}, "notion.search": {"query": "optional text"},
    "notion.read": {"id": "required page ID"},
    "notion.create": {"parent_id": "required existing page ID", "title": "required text", "content": "required text"},
}
